---
version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - athletx
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_data:/data/db"
    restart: always
  
  server:
    image: ghcr.io/athletx-org/athletx-server:1.0.5
    container_name: athletx-server
    ports:
      - "3000:3000"
    depends_on:
    - mongo
    networks:
      - athletx
    environment:
      mongodb_connection_string: mongodb://mongo:27017
    
  client:
    image: ghcr.io/athletx-org/athletx-client:1.2.2
    container_name: athletx-client
    ports:
      - "80:80"
    depends_on:
    - server
    networks:
      - athletx
    environment:
      publicPath: /
      VUE_APP_BASE_URL: http://localhost:3000


networks:
  athletx:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "athletx-net"

volumes:
  mongo_data: